global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ["localhost:9090"]
    basic_auth:
      username: admin
      password: TEST123!

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080